# Generated by Django 5.1 on 2024-08-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0026_alter_profile_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
