# Generated by Django 5.1 on 2024-09-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_alter_bank_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipto', to='bill.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billto', to='bill.customer'),
        ),
    ]
