# Generated by Django 5.1 on 2024-09-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_invoice_ship_to_alter_invoice_invoice_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditem',
            name='dis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
