# Generated by Django 5.1 on 2024-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0029_billeditem_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditem',
            name='taxval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
