# Generated by Django 5.1 on 2024-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0030_billeditem_taxval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billeditem',
            old_name='sigst',
            new_name='cgst_amt',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='taxable_amt',
            new_name='igst_amt',
        ),
        migrations.AddField(
            model_name='billeditem',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billeditem',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billeditem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billeditem',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
