# Generated by Django 5.1 on 2024-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0031_rename_sigst_billeditem_cgst_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeditem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='dis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='taxval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
