# Generated by Django 5.1 on 2024-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_alter_billeditem_amount_alter_billeditem_cgst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cash',
        ),
        migrations.AlterField(
            model_name='billeditem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
