# Generated by Django 5.1 on 2024-09-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0033_remove_profile_cash_alter_billeditem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('no_of_items', models.PositiveIntegerField(default=0)),
                ('taxable_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tgst_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_items', models.ManyToManyField(to='bill.billeditem')),
                ('invoice_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billto', to='bill.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
