# Generated by Django 5.1 on 2024-09-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0035_alter_invoicepurchase_invoice_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
