# Generated by Django 5.1 on 2024-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0038_rename_invoice_to_payment_payment_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
