# Generated by Django 5.1 on 2025-04-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0039_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('bal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_out', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wastage_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.employee')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_processes', to='bill.item')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_processes', to='bill.item')),
            ],
        ),
    ]
