# Generated by Django 5.1 on 2025-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0041_employee_user_processingrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepurchase',
            name='invoice_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
