# Generated by Django 5.1 on 2025-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0042_invoicepurchase_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transport',
            field=models.CharField(max_length=100),
        ),
    ]
